In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Reversed array: [5 4 6 3 2 1]


In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])


In [ ]:
flat1 = array1.flatten()
print("Flatten using flatten():", flat1)

Flatten using flatten(): [1 2 3 2 4 5 1 2 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
comparison = arr1 == arr2
print("Element-wise comparison:\n", comparison)

Element-wise comparison:
 [[ True  True]
 [ True  True]]


In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
most_frequent_x = values[np.argmax(counts)]
indices_x = np.where(x == most_frequent_x)[0]

print("Most frequent in x:", most_frequent_x)
print("Indices in x:", indices_x)

Most frequent in x: 1
Indices in x: [0 5 7 8 9]


In [ ]:
import numpy as np
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values_y, counts_y = np.unique(y, return_counts=True)
most_frequent_y = values_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_y)[0]

print("\nMost frequent in y:", most_frequent_y)
print("Indices in y:", indices_y)


Most frequent in y: 1
Indices in y: [0 1 2]


In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = gfg.sum()
print("Total sum:", total_sum)

Total sum: 45


In [ ]:
row_sum = gfg.sum(axis=1)
print("Row-wise sum:\n", row_sum)

Row-wise sum:
 [[14]
 [16]
 [15]]


In [ ]:
col_sum = gfg.sum(axis=0)
print("Column-wise sum:\n", col_sum)

Column-wise sum:
 [[20  9 16]]


In [ ]:
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diagonal_sum = np.trace(n_array)
print("Diagonal sum:", diagonal_sum)

Diagonal sum: 176


In [ ]:
eigenvalue=np.linalg.eig(n_array)
print("Eigenvalues:", eigenvalues)

Eigenvalues: [98.16835147 28.097044   49.73460452]


In [ ]:
eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors:\n", eigenvectors)

Eigenvectors:
 EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))


In [ ]:
inverse_matrix = np.linalg.inv(n_array)
print("Inverse:\n", inverse_matrix)

Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
det = np.linalg.det(n_array)
print("Determinant:", det)

Determinant: 137180.0000000001


In [ ]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

In [ ]:
product1 = np.dot(p1, q1)
print("Product1:\n", product1)

Product1:
 [[16 19]
 [26 31]]


In [ ]:
cov1 = np.cov(p1.flatten(), q1.flatten())
print("Covariance1:\n", cov1)

Covariance1:
 [[0.66666667 1.        ]
 [1.         1.66666667]]


In [ ]:
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

In [ ]:
product2 = np.dot(p2, q2)
print("Product2:\n", product2)

Product2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
cov2 = np.cov(p2.flatten(), q2.flatten())
print("Covariance2:\n", cov2)

Covariance2:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
print("Inner Product:\n", inner_product)

Inner Product:
 [[17 52]
 [13 62]]


In [ ]:
outer_product = np.outer(x.flatten(), y.flatten())
print("Outer Product:\n", outer_product)

Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
from itertools import product
cartesian_product = np.array(list(product(x.flatten(), y.flatten())))
print("Cartesian Product:\n", cartesian_product)

Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

In [ ]:
abs_array = np.abs(array)
print("Absolute values:\n", abs_array)

Absolute values:
 [[1 2 3]
 [4 5 6]]


In [ ]:
flat = array.flatten()
percentiles_flat = np.percentile(flat, [25, 50, 75])
print("Flattened array percentiles (25th, 50th, 75th):", percentiles_flat)

Flattened array percentiles (25th, 50th, 75th): [-3.5 -0.5  2.5]


In [ ]:
percentiles_cols = np.percentile(array, [25, 50, 75], axis=0)
print("Column-wise percentiles:\n", percentiles_cols)

Column-wise percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]


In [ ]:
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("Row-wise percentiles:\n", percentiles_rows)

Row-wise percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
mean_flat = np.mean(array)
median_flat = np.median(array)
std_flat = np.std(array)

print("Flattened Mean:", mean_flat)
print("Flattened Median:", median_flat)
print("Flattened Std Dev:", std_flat)

Flattened Mean: -0.5
Flattened Median: -0.5
Flattened Std Dev: 3.8622100754188224


In [ ]:
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

print("Column-wise Mean:", mean_col)
print("Column-wise Median:", median_col)
print("Column-wise Std Dev:", std_col)

Column-wise Mean: [-1.5  1.5 -1.5]
Column-wise Median: [-1.5  1.5 -1.5]
Column-wise Std Dev: [2.5 3.5 4.5]


In [ ]:
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Row-wise Mean:", mean_row)
print("Row-wise Median:", median_row)
print("Row-wise Std Dev:", std_row)

Row-wise Mean: [ 0.66666667 -1.66666667]
Row-wise Median: [ 1. -4.]
Row-wise Std Dev: [2.05480467 4.78423336]


In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

In [ ]:
floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)

print("Floor:", floor_vals)
print("Ceiling:", ceil_vals)
print("Truncated:", trunc_vals)
print("Rounded:", round_vals)

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])

In [ ]:
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

Sorted array: [ 10  16  16  52  54  62 453]


In [ ]:
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

Indices of sorted array: [0 3 4 1 5 2 6]


In [ ]:
smallest_4 = np.sort(array)[:4]
print("4 smallest elements:", smallest_4)

4 smallest elements: [10 16 16 52]


In [ ]:
largest_5 = np.sort(array)[-5:][::-1]
print("5 largest elements:", largest_5)

5 largest elements: [453  62  54  52  16]


In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

In [ ]:
int_elements = array[array == np.floor(array)]
print("Integer elements only:", int_elements)

Integer elements only: [1. 2. 3. 2.]


In [ ]:
float_elements = array[array != np.floor(array)]
print("Float elements only:", float_elements)

Float elements only: [1.2 2.2]
